<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Happy Valentine's Kupal</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f8f8;
        }
        .container {
            text-align: center;
        }
        img {
            width: 200px;
            height: auto;
        }
        h1 {
            font-size: 36px;
            color: #ff3366;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="https://www.flaticon.com/svg/static/icons/svg/595/595370.svg" alt="Gift Flower">
        <h1>Happy Valentine's Kupal</h1>
    </div>
</body>
</html>
